### ISSUE TITLE
Music Track Titles Are Still White

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#103]
The white color for the text font makes it difficult to see the music track titles.
![ToT Jan 2-10](https://user-images.githubusercontent.com/59402084/71760258-cb94de00-2e6f-11ea-9537-9e9aa7cf828a.png)
![ToT Jan 2-8](https://user-images.githubusercontent.com/59402084/71760264-d9e2fa00-2e6f-11ea-8697-812e7d740be6.png)

**Comment by sme23** [comment]
fixed by commit 0a1f4080ce0a2d8f053ae5be4359cd9ba62ccbbe
