### ISSUE TITLE
Lack of Class Growths for Vergil

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#105]
I recently made class growths for Vergil on the spreadsheet so his lord class has class growths to add on top of his personal growths. His current growths are noticeably below average compared to other Lords like Elle and Rodin.
![ToT Jan 2-11](https://user-images.githubusercontent.com/59402084/71760397-e7997f00-2e71-11ea-8bd5-edd286a5e340.png)

**Comment by sme23** [comment]
![FireEmblem3Universes_059](https://user-images.githubusercontent.com/24559482/71772922-01929a80-2f22-11ea-8f1d-2c0d4048fd3a.png)
