### ISSUE TITLE
Reverted Back to Vanilla Intro

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#109]
In this patch I received to play test again, I noticed that the intro is reverted back to the vanilla intro for FE8. I'm not really sure why this happens?

![ToT Jan 14-0](https://user-images.githubusercontent.com/59402084/72688160-71c02500-3ab9-11ea-86ab-007211009946.png)
![ToT Jan 14-3](https://user-images.githubusercontent.com/59402084/72688334-e9db1a80-3aba-11ea-9ff8-1761613c29ef.png)
![ToT Jan 14-6](https://user-images.githubusercontent.com/59402084/72688336-ecd60b00-3aba-11ea-82d1-cee76d7e313d.png)
![ToT Jan 14-5](https://user-images.githubusercontent.com/59402084/72688339-f3fd1900-3aba-11ea-9df9-5d4a6a6ec074.png)

**Comment by sme23** [comment]
fixed a bit ago
