### ISSUE TITLE
Scripted Vollster Battle in AB2 Can Softlock & PJ2 Bear Syndrome

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#110]
I'm not sure what the conditions are that caused this in the first place but let me preface. 

There were some new events scripted into AB2 where Vollster comes out of the center village on the map to say that he is sick to laying around and wants to fight. The fight is supposed to be Vollster inflicting a critical hit on the enemy merc but that can never happen and the game displays the cursor on the village only for nothing to happen. You cannot progress if that happens and I tried soft resetting again and again. Even restarting the entire route, it can still happen on your first encounter.

![ToT Jan 14-41](https://user-images.githubusercontent.com/59402084/72688256-29553700-3aba-11ea-9835-41fba91da251.png)

Even if Vollster does appear and fights, chances are that he will still die anyway. He suffers the same fate as the bear enemy in PJ2 where he gets cornered and gets dogpiled.

![ToT Jan 14-46](https://user-images.githubusercontent.com/59402084/72688281-59043f00-3aba-11ea-8fd7-b052b0991848.png)
![ToT Jan 14-51](https://user-images.githubusercontent.com/59402084/72688285-5e618980-3aba-11ea-8f6f-5d100199029c.png)

**Comment by sme23** [comment]
fixed in commit 9353bcf7737db02f5792687fb9e1dcf73ebd17d2
