### ISSUE TITLE
Unbalanced Enemy Stats

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#111]
I believe this issue is already well known but I feel like I have to put this up here otherwise I fear that the enemies will not change. 

The problem is that **enemies in this game are tough to kill all for the wrong reasons**. Your units are not strong enough to take them down reliably especially when the hack throws very dense reinforcements and bulky enemy types (Cav Reinforcements in AB3). You are not prepared in the slightest since _you rarely ever get effective weapons to kill them and they are not enough_ to kill the enemies reliably since their bulk is that high.

I argue that these **enemies definitely need to be nerfed in terms of stats**; some enemies are too strong to take down. Their offenses should be nerfed too since each route is not very bulky to handle them in high numbers. This painfully true in Rodin's route where his allies do not live beyond 2 hits. Elle's route gets overwhelmed with frequent reinforcements and minibosses in AB3. 

Some enemies like mages should not have 10 defense and res. Armors, in general, should **not** be fast enough to not get doubled by mages ever; they should not have good res either. Physical enemies should not have magic and magical enemies should not have a high strength stat.
![ToT Jan 14-59](https://user-images.githubusercontent.com/59402084/72688475-74704980-3abc-11ea-94e5-729b6a80e035.png)
![ToT Jan 14-62](https://user-images.githubusercontent.com/59402084/72688478-7a662a80-3abc-11ea-878a-19d5a04b89a0.png)
![ToT Jan 14-63](https://user-images.githubusercontent.com/59402084/72688683-818e3800-3abe-11ea-8271-7c84eb118493.png)

There are potential workarounds to these enemies such as allowing the player to easily gain access to effective weapons like hammers, horseslayers, and bows very early on in some shop/armory and having them be enemy drops. However, it is only a band-aid solution because enemy stats will still be too strong to deal with later on.

**Comment by sme23** [comment]
they were nerfed but also probably too much, possibly worth reevaluating at a later date
