### ISSUE TITLE
Introduction cutscene is unskippable

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#18]
Pressing start on the first cutscene of the game where the three routes are briefly explained has no effect. As a result, the entirety of the cutscene must be viewed every time a new game is started, in contrast to every other cutscene in the game. A save state has been provided for easy access.
[example save state.zip](https://github.com/Kirbseverywhere/Fire-Emblem-3-Universes/files/3828546/example.save.state.zip)
![FireEmblem3Universes_01](https://user-images.githubusercontent.com/30606600/68545648-dfb7e400-03c6-11ea-9908-b476d428baab.png)

**Comment by Kirbseverywhere** [comment]
Commit 5d271e6 fixes it. EVBIT_MODIFY 0x1 at the beggining of the events made the cutscene unskippable.
