### ISSUE TITLE
Tale select visual bug

### ISSUE THREAD

**Issue by sme23** [Kirbseverywhere/Fire-Emblem-3-Universes#20]
Following the opening cutscene and the chapter introduction for tale select, the screen fades in to a background different from the house select/unit customization screen's background before loading said screen.  It should load the same bg before loading the house selection screen as the one on that screen.

**Comment by Kirbseverywhere** [comment]
Loading a background is a temporary solution as not loading anything before trying to load the House Selection screen ends up in the screen being hidden(but with everything else working properly).

**Comment by Darrman** [comment]
Blank background loaded instead.
