### ISSUE TITLE
House Selection Input Method

### ISSUE THREAD

**Issue by sme23** [Kirbseverywhere/Fire-Emblem-3-Universes#21]
It is not clear that the Select button is the one used to select your house. Putting an input prompt on the screen such as other menus have (see the Guide menu's Sort button indicator) and/or letting the A and/or Start buttons also function, as those are the natural first choice buttons.

**Comment by Kirbseverywhere** [comment]
583a5e1800afb45f9ce454177f47ede138b8d9bc changes the input to either start, select, or a on any house.
