### ISSUE TITLE
Stat Screen Misalignment

### ISSUE THREAD

**Issue by sme23** [Kirbseverywhere/Fire-Emblem-3-Universes#24]
When rescuing, the Skill and Spd debuff arrows appear over Mag and Skill respectively. The rescuing icon blinks next to Con instead of Trv. The being rescued indicator blinks underneath the Affinity icon. The first two of these can be controlled via definitions in `ModularStatScreen.event`.

**Comment by Kirbseverywhere** [comment]
Fixed by 22b1b59a6894c2253355f22d83ca60d4fe02f7eb
