### ISSUE TITLE
Accessory Item Use Descriptions

### ISSUE THREAD

**Issue by sme23** [Kirbseverywhere/Fire-Emblem-3-Universes#26]
Accessories lack item use descriptions, only standard descriptions. Thus, the item use description box is empty when going into a unit's inventory to equip an accessory.

**Comment by Darrman** [comment]
Added in commit https://github.com/Kirbseverywhere/Fire-Emblem-3-Universes/commit/1d90acdee6730fcebe010e564f7e62505f139e49.
