### ISSUE TITLE
[PJ2] Chapter title does not appear when file loaded

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#38]
Instead of "Ch. 2: Persecution", a blank title card appears. 

![FireEmblem3Universes_05](https://user-images.githubusercontent.com/30606600/69009708-f83c7700-094f-11ea-953c-040039b7b56d.png)

**Comment by Kirbseverywhere** [comment]
Fixed by cf8e1b0
