### ISSUE TITLE
Unarmed cleric crashes the game

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#39]
Should a cleric be attacked holding no weapon or staff, the game will begin screeching. This can be worked around by holding L before combat. The priest and troubadour both have functional unarmed animations. (See #32.)

**Comment by sme23** [comment]
Animation table is only repointed up to 0xA0 and cleric unarmed anim in vanilla is in the 0xC0 range for some reason, thereby no longer being present

**Comment by sme23** [comment]
Fixed in #62
