### ISSUE TITLE
[AB1] Villages get destroyed infinitely

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#40]
Like #36, the villages get destroyed over and over again without end due to the lack of tile changes. 
![FireEmblem3Universes_07](https://user-images.githubusercontent.com/30606600/69011716-6f303a80-0965-11ea-9b7d-becf038c174b.png)

**Comment by Kirbseverywhere** [comment]
Untested, but should be fixed by ad3a1f1df1afd00c4d2e027d319bde62ec2e70c6
