### ISSUE TITLE
[PJ3] All tile changes non-functional

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#42]
Chests do not give items, despite Locktouch allowing them to be picked. Doors are also non-functional, despite consuming lockpick uses.

**Comment by Kirbseverywhere** [comment]
Untested, but should be fixed by 288e5f37e8b04d3c98ec23fc0c07accbf6808fdf (ignore the name, that was a mistake)
