### ISSUE TITLE
PJ2 Bear Death Softlock

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#65]
Enemies bumrush the bear and kill it preemptively before Turn 3 happens. Once the map reaches Turn 3, the game cannot progress any further since the bear that was meant to move on Turn 3 is dead. 
![ToT Dec 30-93](https://user-images.githubusercontent.com/59402084/71636518-4ea30380-2be6-11ea-829a-88dd4b5e9f80.png)

**Comment by Darrman** [comment]
Fixed by https://github.com/Kirbseverywhere/Fire-Emblem-3-Universes/commit/8320b283f29b17526fe149613eadd58b0dcbe29d.
