### ISSUE TITLE
PJ2 Lack of Cave Cutscene Background

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#66]
A volcano does not really show the interior of a cave that well even though its the closest bg possible at the moment.
![ToT Dec 31 v3-55](https://user-images.githubusercontent.com/59402084/71636672-392ed900-2be8-11ea-86ec-b415d49b943c.png)

**Comment by Darrman** [comment]
Fixed by https://github.com/Kirbseverywhere/Fire-Emblem-3-Universes/commit/0a9e7e8182d1ad2ca6340775b6c1a2dbbd35c9f9.
