### ISSUE TITLE
[PJ3] Green units attack captured units

### ISSUE THREAD

**Issue by Darrman** [Kirbseverywhere/Fire-Emblem-3-Universes#69]
![FireEmblem3Universes_30](https://user-images.githubusercontent.com/30606600/71637398-73c16180-2c3a-11ea-89d4-f9a7959db406.png)
If a unit is captured in PJ2, Lenato will begin attacking them even though she is not an enemy. See attached save state.
[mean greens pj3.zip](https://github.com/Kirbseverywhere/Fire-Emblem-3-Universes/files/4013719/mean.greens.pj3.zip)

**Comment by sme23** [comment]
nice

**Comment by sme23** [comment]
Actually going to reopen this because the fix I did was just to change AI but they'll still try to attack and that should be fixed

**Comment by sme23** [comment]
fixed with making hostile NPCs a toggle
