### ISSUE TITLE
Acrobat does not work 

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#70]
Terrain costs still apply
![ToT Dec 29-105](https://user-images.githubusercontent.com/59402084/71637498-7c457800-2bf9-11ea-8ca2-45274cf1ec67.png)
![ToT Dec 29-106](https://user-images.githubusercontent.com/59402084/71637500-7e0f3b80-2bf9-11ea-95a1-f993b1a2dc31.png)

**Comment by sme23** [comment]
Fixed by commit 797699da9e8e6f6377257e95021eb03f6d4c626e
