### ISSUE TITLE
AB1 Mage Reinforcement Does Not Chase

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#74]
The archer chases you as they should but the mage does not for some reason. The mage only attacks if someone is in their attack range.

![ToT Dec 31 v3-68](https://user-images.githubusercontent.com/59402084/71646734-5f17b480-2ca0-11ea-8c96-1b6b1f7b9a55.png)

**Comment by Darrman** [comment]
Fixed by https://github.com/Kirbseverywhere/Fire-Emblem-3-Universes/commit/f04e422bf984c4fc5fc1e5958b88bb4211a9ce4e
