### ISSUE TITLE
AB3 Inconsistent Battle Backgrounds

### ISSUE THREAD

**Issue by Xebdal** [Kirbseverywhere/Fire-Emblem-3-Universes#75]
This map uses the plains tileset but the battle background uses the night time plains background instead. It also uses the desert background on the right side of the map.
![ToT Dec 31 v3-75](https://user-images.githubusercontent.com/59402084/71646859-5e801d80-2ca2-11ea-84a8-e49506736d19.png)
![ToT Dec 31 v3-76](https://user-images.githubusercontent.com/59402084/71646861-6344d180-2ca2-11ea-8fb0-bb24ff1d446c.png)
![ToT Dec 28-73](https://user-images.githubusercontent.com/59402084/71646880-90917f80-2ca2-11ea-88f8-844300ba520b.png)

**Comment by sme23** [comment]
Should be fixed by commit d719a19c4261ed621603f968d810419fec227065
